from trade_license_cbt.models.question_model import Question

SAMPLE_QUESTIONS: list[Question] = [
    Question(id=1, subject="무역규범",
             question_text="무역계약에서 청약(Offer)의 효력이 소멸되는 경우가 아닌 것은?",
             options=["① 청약의 철회", "② 청약의 거절", "③ 반대청약", "④ 청약의 공시"],
             answer="④ 청약의 공시",
             explanation="청약 효력 소멸 사유는 철회, 거절, 반대청약, 기간만료 등이며 '공시'는 해당되지 않습니다.",
             page_number=1),
    Question(id=2, subject="무역규범",
             question_text="인코텀즈(Incoterms) 2020에서 매도인의 위험 부담이 가장 큰 조건은?",
             options=["① EXW", "② FCA", "③ CIF", "④ DDP"],
             answer="④ DDP",
             explanation="DDP(Delivered Duty Paid)는 목적지까지의 모든 비용과 위험을 매도인이 부담하는 조건입니다.",
             page_number=1),
    Question(id=3, subject="무역결제",
             question_text="신용장(L/C)에서 일람출급(Sight) 어음을 사용할 때 대금 지급 시기는?",
             options=["① 선적 후 30일", "② 서류 제시 즉시", "③ 만기일", "④ 선적일"],
             answer="② 서류 제시 즉시",
             explanation="일람출급 어음은 제시와 동시에 지급이 이루어집니다.",
             page_number=2),
    Question(id=4, subject="무역결제",
             question_text="추심결제(Collection) 방식 중 D/P(Documents against Payment)에 대한 설명으로 옳은 것은?",
             options=["① 인수 후 서류 인도", "② 지급 후 서류 인도", "③ 신용장 개설 필요", "④ 은행 지급 보증"],
             answer="② 지급 후 서류 인도",
             explanation="D/P는 수입상이 대금을 지급해야만 선적서류를 인도받을 수 있는 방식입니다.",
             page_number=2),
    Question(id=5, subject="무역물류",
             question_text="해상화물운송장(Sea Waybill)과 선하증권(B/L)의 차이점으로 옳은 것은?",
             options=["① 해상화물운송장은 유통성 있음", "② 선하증권은 권리증권임", "③ 해상화물운송장 원본 3통 발행", "④ 선하증권은 지시식 불가"],
             answer="② 선하증권은 권리증권임",
             explanation="선하증권(B/L)은 유통성 있는 권리증권이며, 해상화물운송장은 비유통성 서류입니다.",
             page_number=3),
    Question(id=6, subject="무역물류",
             question_text="컨테이너 운송에서 FCL(Full Container Load)에 대한 설명으로 옳은 것은?",
             options=["① 혼재화물 운송", "② 단일 화주가 컨테이너 전체 사용", "③ 소량 화물 전용", "④ 항공 전용 용어"],
             answer="② 단일 화주가 컨테이너 전체 사용",
             explanation="FCL은 한 화주가 컨테이너 하나를 전용으로 사용하는 방식입니다.",
             page_number=3),
    Question(id=7, subject="무역규범",
             question_text="WTO 분쟁해결기구(DSB)의 패널 보고서 채택 방식은?",
             options=["① 만장일치", "② 역전컨센서스(Negative Consensus)", "③ 단순다수결", "④ 의장 단독 결정"],
             answer="② 역전컨센서스(Negative Consensus)",
             explanation="WTO DSB는 보고서에 반대하는 전원 합의가 없으면 자동 채택되는 역전컨센서스 방식을 사용합니다.",
             page_number=4),
    Question(id=8, subject="무역영어",
             question_text="무역 서신에서 'We acknowledge receipt of your letter dated ~'의 의미로 옳은 것은?",
             options=["① 서신 발송 확인", "② 서신 수신 확인", "③ 주문 취소 통보", "④ 대금 청구"],
             answer="② 서신 수신 확인",
             explanation="'acknowledge receipt of'는 '~를 수령했음을 확인한다'는 뜻입니다.",
             page_number=4),
    Question(id=9, subject="무역결제",
             question_text="무역금융에서 포페이팅(Forfaiting)의 특징으로 옳은 것은?",
             options=["① 소구권(Recourse) 있음", "② 단기 금융(90일 이내)", "③ 무소구권(Without Recourse)", "④ 국내 거래 전용"],
             answer="③ 무소구권(Without Recourse)",
             explanation="포페이팅은 수출채권을 무소구 방식으로 매입하는 중장기 무역금융입니다.",
             page_number=5),
    Question(id=10, subject="무역물류",
             question_text="항공화물운송장(AWB)의 성격으로 옳은 것은?",
             options=["① 유통증권", "② 권리증권", "③ 비유통성 화물수취증", "④ 보험증권"],
             answer="③ 비유통성 화물수취증",
             explanation="AWB는 선하증권과 달리 유통성이 없으며 단순한 화물수취증 겸 운송계약서입니다.",
             page_number=5),
]
